#!/usr/bin/env python3
"""Stage a licensed external G1 asset for local use.

The default symlink mode does not duplicate third-party binaries.  Copy mode
is available for an isolated machine, but the destination is deliberately
ignored by git and the two upstream license notices are copied alongside it.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


def prepare(source_root: Path, destination: Path, mode: str = "symlink") -> Path:
    source_root = source_root.expanduser().resolve()
    destination = destination.expanduser().resolve()
    required = {
        "g1.usd": source_root / "usd/g1.usd",
        "g1.urdf": source_root / "urdf/g1.urdf",
        "g1.xml": source_root / "mjcf/g1.xml",
        "mesh": source_root / "mesh/G1",
    }
    missing = [str(path) for path in required.values() if not path.exists()]
    if missing:
        raise FileNotFoundError("missing G1 asset entries: " + ", ".join(missing))
    if destination.exists() and any(destination.iterdir()):
        raise FileExistsError(f"destination is not empty: {destination}")
    destination.mkdir(parents=True, exist_ok=True)
    for name, source in required.items():
        target = destination / name
        if mode == "symlink":
            target.symlink_to(source, target_is_directory=source.is_dir())
        elif mode == "copy":
            if source.is_dir():
                shutil.copytree(source, target)
            else:
                shutil.copy2(source, target)
        else:
            raise ValueError("mode must be symlink or copy")

    project_license = source_root.parents[2] / "LICENSE"
    mesh_license = source_root / "mesh/G1/LICENSE"
    for label, source in (("LICENSE.protomotions", project_license),
                          ("LICENSE.unitree_g1", mesh_license)):
        if source.is_file():
            shutil.copy2(source, destination / label)
    (destination / "ASSET_SOURCE.md").write_text(
        "# Local G1 asset staging\n\n"
        f"Source: `{source_root}`\n\n"
        "This directory is generated by `setup/prepare_g1_asset.py`. Keep "
        "LICENSE.protomotions and LICENSE.unitree_g1 with any deployment; "
        "review the NVIDIA non-commercial research/evaluation terms before "
        "redistribution or commercial use.\n",
        encoding="utf-8",
    )
    return destination


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", required=True, type=Path,
                        help=".../protomotions/data/assets")
    parser.add_argument("--destination", required=True, type=Path)
    parser.add_argument("--mode", choices=("symlink", "copy"), default="symlink")
    args = parser.parse_args(argv)
    print(prepare(args.source_root, args.destination, args.mode))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
